// <auto-generated />
namespace EF_Tekrar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmailEklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailEklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "201610251327086_Email Eklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
