//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MhrsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doktor()
        {
            this.Randevu = new HashSet<Randevu>();
            this.RandvuSaati_Doktor = new HashSet<RandvuSaati_Doktor>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> CinsiyetId { get; set; }
        public Nullable<int> UzmanlıkId { get; set; }
        public Nullable<int> HastaneId { get; set; }
    
        public virtual Cinsiyet Cinsiyet { get; set; }
        public virtual Hastane Hastane { get; set; }
        public virtual Klinik Klinik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandvuSaati_Doktor> RandvuSaati_Doktor { get; set; }
    }
}
