//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MhrsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastane_Klinik
    {
        public int Id { get; set; }
        public int HastaneId { get; set; }
        public int KlinikId { get; set; }
    
        public virtual Hastane Hastane { get; set; }
        public virtual Klinik Klinik { get; set; }
    }
}
