//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MhrsWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MhrsWebDBEntities : DbContext
    {
        public MhrsWebDBEntities()
            : base("name=MhrsWebDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinsiyet> Cinsiyet { get; set; }
        public virtual DbSet<Command> Command { get; set; }
        public virtual DbSet<Doktor> Doktor { get; set; }
        public virtual DbSet<Hastane> Hastane { get; set; }
        public virtual DbSet<Hastane_Klinik> Hastane_Klinik { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<Klinik> Klinik { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Randevu> Randevu { get; set; }
        public virtual DbSet<RandevuSaati> RandevuSaati { get; set; }
        public virtual DbSet<RandvuSaati_Doktor> RandvuSaati_Doktor { get; set; }
        public virtual DbSet<Sehir> Sehir { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
