//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MhrsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandvuSaati_Doktor
    {
        public System.DateTime RandevuTarihi { get; set; }
        public int RandevuSaatiId { get; set; }
        public int DoktorId { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual RandevuSaati RandevuSaati { get; set; }
    }
}
